### ISSUE TITLE
exif_read_data - File not supported

### ISSUE THREAD

**Issue by be-schmidt** [snipiba/oc-memetadata-plugin#1]
Hi @snipiba,

i get the error exif_read_data: "File not supported" on some file types (p.e. png) in the media manager, if i try to edit the meta data.

A possible solution would be to change line 58 in file public/plugins/snipi/memetadata/classes/MEMetadata.php to:
`$widget->vars['exif'] = @exif_read_data(storage_path('app/media' . $path));`

Adding the @ prefix surpresses the error dialog.

Nice greetings
Bernd

**Comment by snipiba** [comment]
Fix in version 1.0.9
