### ISSUE TITLE
Can't install the plugin on OCMS3

### ISSUE THREAD

**Issue by Zmove** [snipiba/oc-memetadata-plugin#2]
Hello,

There is a small problem with your plugin, when I try to install it in a fresh october cms 3.x install, I get the following error : 

![image](https://user-images.githubusercontent.com/1314678/218299588-9e16bab9-d4d6-4790-b51c-c69cc3af0ce4.png)

Best regards,

**Comment by snipiba** [comment]
created release version 1.0
